class Global{
  static bool isIos = false;
  static List apps = [
    {
      'image': 'assets/images/logo-1.png',
      'name': 'Nest',
      'title': 'Nest Labs Inc.',
      'star': '4.2',
      'user': '1K+',
      'image-1': 'https://vectorified.com/images/nest-thermostat-icon-28.png',
      'image-2': 'https://content.nexus.support.com/5b557b9559124044bb566bfc31a09c80/7eb5f2c0f49411e7bb4dcdd3919dc6c2.png',
    },
    {
      'image': 'assets/images/logo-2.png',
      'name': 'Nike Training Club',
      'title': 'Nike, Inc.',
      'star': '4.1',
      'user': '100K+',
      'image-1': 'http://a4.mzstatic.com/us/r30/Purple4/v4/8a/7a/f3/8a7af375-7e8e-9330-0d3f-d28440d11927/mzl.xrfprswe.png',
      'image-2': 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/03ae6483503639.5d3ee0165522c.jpg',
    },
    {
      'image': 'assets/images/logo-3.png',
      'name': 'Tasty',
      'title': 'Buzzfeed',
      'star': '3.8',
      'user': '10K+',
      'image-1': 'https://i.pinimg.com/originals/9a/1e/03/9a1e034ba48b4bd66a1893ef6696c59c.jpg',
      'image-2': 'https://blog.hubspot.com/hs-fs/hubfs/Google%20Drive%20Integration/What%20Is%20User%20Interface%20(UI)%20Design-4.jpeg?width=1500&name=What%20Is%20User%20Interface%20(UI)%20Design-4.jpeg',
    },
    {
      'image': 'assets/images/app.jpg',
      'name': 'Whatsapp',
      'title': 'Whatsapp LLC',
      'star': '4.6',
      'user': '500M+',
      'image-1': 'https://pluspng.com/img-png/whatsapp-logo-png-whatsapp-logo-png-transparent-amp-svg-vector-pluspng-2400x2400.png',
      'image-2': 'https://cdn.mos.cms.futurecdn.net/G9eQCBiup4zay4usqFNPRP.jpg',
    },
    {
      'image': 'assets/images/note.jpg',
      'name': 'Noted - Notepad',
      'title': 'Notes',
      'star': '3.5',
      'user': '1M+',
      'image-1': 'http://1.bp.blogspot.com/-pVBvChI8N-E/VJ_pHB6Y56I/AAAAAAAAANM/Qcac0jLS0QM/s1600/MetroUI-Apps-Notepad-icon.png',
      'image-2': 'https://i.pinimg.com/originals/9c/d1/ab/9cd1abeb6c45ce9a8ef4ebcfbf0fe15d.png',
    },
  ];
  static List newApps = [
    {
      'image': 'assets/images/logo-6.jpg',
      'name': 'Google Translate',
      'title': 'Google LLC',
      'star': '4.6',
      'user': '1M+',
      'image-1': 'https://www.patchworkoftips.com/wp-content/uploads/2015/08/google_translate_main-1280x720-1.jpg',
      'image-2': 'https://cdn.mos.cms.futurecdn.net/NM6Lj6HCKntXNWVs3z4kGg.jpg',
    },
    {
      'image': 'assets/images/logo-4.png',
      'name': 'Weather',
      'title': 'Weather Radar team',
      'star': '4.1',
      'user': '100K+',
      'image-1': 'https://cdn.freebiesupply.com/images/thumbs/2x/ios14-weather-app-icon-w78.jpg',
      'image-2': 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/42737f54398239.595b72884e874.png',
    },
    {
      'image': 'assets/images/logo-5.png',
      'name': 'Airbnb',
      'title': 'Airbnb',
      'star': '3.1',
      'user': '1K+',
      'image-1': 'https://logodix.com/logo/568313.png',
      'image-2': 'https://i.pinimg.com/originals/21/be/4e/21be4e08592aebd5a76f78610425c398.png',
    },
    {
      'image': 'assets/images/logo-7.png',
      'name': 'Snapchat',
      'title': 'Snap Inc',
      'star': '4.1',
      'user': '5M+',
      'image-1': 'https://logos-world.net/wp-content/uploads/2020/04/Snapchat-Logo-2013-2019.png',
      'image-2': 'https://cdn.dribbble.com/users/4103036/screenshots/7786430/media/76be9d031e6bcef8c37207a606b32674.jpg',
    },
    {
      'image': 'assets/images/insta.jpg',
      'name': 'Instagram',
      'title': 'Instagram',
      'star': '4.8',
      'user': '100M+',
      'image-1': 'https://trueinteractive.com/wp-content/uploads/2019/06/Instagram-app-logo.jpg',
      'image-2': 'https://cdn.dribbble.com/users/693438/screenshots/9940370/dribbble_shot_hd_-_3_4x.png',
    },
  ];
  static List suggestion = [
    {
      'image': 'assets/images/logo-8.jpg',
      'name': 'Gallery',
      'title': 'Studio Inc.',
      'star': '4.2',
      'user': '1M+',
      'image-1': 'https://cdn.osxdaily.com/wp-content/uploads/2015/04/photos-app-icon-mac.jpg',
      'image-2': 'https://cdn.dribbble.com/users/2376224/screenshots/4761564/gallery_app_icon.gif',
    },
    {
      'image': 'assets/images/logo-9.jpg',
      'name': 'Amazon',
      'title': 'Amazon Mobile LLC',
      'star': '4.8',
      'user': '10M+',
      'image-1': 'https://wallsdesk.com/wp-content/uploads/2016/10/Amazon-Widescreen.png',
      'image-2': 'https://cdn.dribbble.com/users/3111348/screenshots/6458622/amazon_redesigned___1_4x.jpg',
    },
    {
      'image': 'assets/images/logo-10.png',
      'name': 'Facebook',
      'title': 'Meta platforms, Inc.',
      'star': '4.1',
      'user': '20M+',
      'image-1': 'https://1000logos.net/wp-content/uploads/2016/11/Facebook-logo.png',
      'image-2': 'https://cdn.dribbble.com/users/1637201/screenshots/4723550/image.png',
    },
    {
      'image': 'assets/images/logo-11.jpg',
      'name': 'Linkedin',
      'title': 'Linkedin',
      'star': '3.8',
      'user': '1M+',
      'image-1': 'https://wallpapercave.com/wp/wp4421266.jpg',
      'image-2': 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/871efa77456407.5c881fb1e13d3.gif',
    },
    {
      'image': 'assets/images/logo-12.jpg',
      'name': 'Twitter',
      'title': 'Twitter, Inc.',
      'star': '4.4',
      'user': '4M+',
      'image-1': 'https://www.nvcs.co.uk/wp-content/uploads/Twitter_logo_bird_transparent_png-768x624.png',
      'image-2': 'https://i.pinimg.com/originals/55/67/0e/55670eedd61fbaa549793a25ff9e04bf.png',
    },
  ];
  static List game = [
    {
      'image': 'assets/images/pool.jpg',
      'name': 'King of pool',
      'title': 'Uken games',
      'star': '3.5',
      'user': '5M+',
      'image-1': 'https://gamedva.com/wp-content/uploads/kingsofpool.jpg',
      'image-2': 'https://i.ytimg.com/vi/h-c5yAV7GPg/maxresdefault.jpg',
    },
    {
      'image': 'assets/images/wcc.jpg',
      'name': 'WCC-2',
      'title': 'Nextwave Multimedia',
      'star': '4.5',
      'user': '100K+',
      'image-1': 'https://i0.wp.com/androidupdate.net/wp-content/uploads/2018/09/World-Cricket-Championship-2-Game-Review.jpg?fit=988%2C556&ssl=1',
      'image-2': 'https://i.ytimg.com/vi/2XSu15CBItk/maxresdefault.jpg',
    },
    {
      'image': 'assets/images/shoot.jpg',
      'name': 'Shooting 3D',
      'title': 'shoot gamer',
      'star': '3.2',
      'user': '1M+',
      'image-1': 'https://gamersanctum.com/shooter/wp-content/uploads/sites/3/2016/10/Gameplay-Crossfire-1168x670.jpg',
      'image-2': 'https://cdn.wallpapersafari.com/58/25/JElZeF.jpg',
    },
    {
      'image': 'assets/images/race.jpg',
      'name': 'Real Racing 3D',
      'title': 'Speed gun',
      'star': '4.4',
      'user': '10M+',
      'image-1': 'https://image.winudf.com/v2/image1/Y29tLmdhbWV4aXMucmFjaW5nLmZlcm9jaXR5LmFwcHNfc2NyZWVuXzE2XzE1OTU2NjU1NDFfMDU4/screen-16.jpg?fakeurl=1&type=.jpg',
      'image-2': 'https://www.touchtapplay.com/wp-content/uploads/2014/03/Real-Racing-3.jpg',
    },
    {
      'image': 'assets/images/traffic.jpg',
      'name': 'Traffic Racer',
      'title': 'Soner Kara',
      'star': '4.1',
      'user': '10k+',
      'image-1': 'https://i.ytimg.com/vi/MvISKo2RNp4/maxresdefault.jpg',
      'image-2': 'https://images-na.ssl-images-amazon.com/images/I/A1pv-GJJfsL.png',
    },
    {
      'image': 'assets/images/bottle.jpg',
      'name': 'Bottle Flip 3D',
      'title': 'Casual Games',
      'star': '3.4',
      'user': '500K+',
      'image-1': 'https://i.ytimg.com/vi/PsSesdXSI_I/hqdefault.jpg',
      'image-2': 'https://androidvip.net/uploads/posts/2019-06/1559665675_impossible-bottle-flip-android.jpg',
    },
  ];
}